############# English navigation ##############

# main menu

[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "JobRunr Pro"
pageRef = "/pro"
weight = 2


[[main]]
name = "Blog"
pageRef = "/blog"
weight = 3


[[main]]
name= "Documentation"
pageRef = "/documentation"
weight = 3
[main.params]
hasChildren = false


[[main]]
name= "Guides"
pageRef = "/guides"
weight = 3

# [[main]]
# name = "All Pages"
# weight = 4

# [[main]]
# parent = "All Pages"
# name = "Integration"
# pageRef = "/integration"
# weight = 3

# [[main]]
# parent = "All Pages"
# name = "Changelog"
# pageRef = "/changelog"
# weight = 4




# [[main]]
# parent = "All Pages"
# name = "404 Page"
# pageRef = "/404"
# weight = 10





# footer menu left
[[footer_01]]
name = "Blog"
url = "/blog"
weight = 3

[[footer_01]]
name = "Contact"
pageRef = "/contact"
weight = 5

[[footer_02]]
name = "Terms"
url = "/licensing/info/"
weight = 1

[[footer_02]]
name = "Privacy Policy"
url = "/privacy"
weight = 2

[[footer_02]]
name = "About JobRunr"
pageRef = "/about"
weight = 3

